### ISSUE TITLE
All users page

### ISSUE THREAD

**Issue by ncannasse** [jasononeil/haxelib#18]
Do not list downloads count in http://preview.lib.haxe.org/u/ (still sort by most downloaded) this will make the page more readable

**Comment by markknol** [comment]
I think its nice to display the download count. This makes this page also a positive ranking system. Maybe it works with smaller font size too.

**Comment by Simn** [comment]
I agree with Nicolas, that's just too much noise.

**Comment by ncannasse** [comment]
@markknol we can have the downloads count on project page, per-user page, all projects page, just not on this page where this is not really what one might look for ;)
