### ISSUE TITLE
Put lib.haxe live 

### ISSUE THREAD

**Issue by markknol** [jasononeil/haxelib#27]
:smile: the new api.haxe is already live, would be great if we can put lib.haxe also live with this 3.2 release. 

Is there anything I can do to help?

**Comment by Simn** [comment]
I would also like to know what the timeframe is on that. Are we gonna get this live soon or do you want to pull some stunt at WWX?

**Comment by ncannasse** [comment]
I discussed it with jaon, we will do it for WWX, keep it a surprise ;)
