### ISSUE TITLE
Stats arent up to date?

### ISSUE THREAD

**Issue by markknol** [jasononeil/haxelib#29]
http://lib.haxe.org/p/tink_xml/
How much time does it take before the stats are updated?

**Comment by ncannasse** [comment]
It seems that download stats are not saved, but this might be because of @back2dos since this is done as part of haxelib API

**Comment by back2dos** [comment]
I'm not really sure where this comes from. The call is made in the client:

https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L824

And processed by the server: 

https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Repo.hx#L306

I'll look into this next week.

**Comment by back2dos** [comment]
My guess is maybe the reimplementation of SemVer as an abstract over String caused small changes which make this query fail: https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Repo.hx#L296

And then postInstall is abruptly cancelled by this: https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Repo.hx#L304

And the error is silenced by this pokemon clause: https://github.com/HaxeFoundation/haxelib/blob/master/src/tools/haxelib/Main.hx#L825

**Comment by ncannasse** [comment]
Let's blame them all !

**Comment by back2dos** [comment]
I'm not blaming, only thinking out loud ;)

**Comment by markknol** [comment]
Lol Gotta catch em all!

**Comment by Simn** [comment]
Haha, "pokemon clause" is brilliant.
