### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jasononeil** [jasononeil/haxelib#4]
Do we:
1. Use a simple keyword search on title / description, or
2. Use a google web search targetting haxe.org

And then....
- [ ] Fix the search box in the nav bar
- [ ] Style the search results page
- [ ] If we are doing our own results, figure out a good balance of popularity / relevance to search on.

**Comment by Simn** [comment]
Could we get a quick fix for that massive search bar?

**Comment by jasononeil** [comment]
Woah, hadn't opened it in Chrome.  I'll fix that now.

**Comment by jasononeil** [comment]
I fixed the giant search that I saw in Chrome.  If it's still broken for
you post a screenshot and browser version so I can look into it.

**Comment by Simn** [comment]
Looks good now, thanks!
